//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workspace_Management_System.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workspace_Management_System.Application.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active service with the same name already exists..
        /// </summary>
        internal static string ActiveServiceWithSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("ActiveServiceWithSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic service name cannot exceed 100 characters..
        /// </summary>
        internal static string ArabicServiceNameMaxLength {
            get {
                return ResourceManager.GetString("ArabicServiceNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic service name is required..
        /// </summary>
        internal static string ArabicServiceNameRequired {
            get {
                return ResourceManager.GetString("ArabicServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted service not found..
        /// </summary>
        internal static string DeletedServiceNotFound {
            get {
                return ResourceManager.GetString("DeletedServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English service name cannot exceed 100 characters..
        /// </summary>
        internal static string EnglishServiceNameMaxLength {
            get {
                return ResourceManager.GetString("EnglishServiceNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English service name is required..
        /// </summary>
        internal static string EnglishServiceNameRequired {
            get {
                return ResourceManager.GetString("EnglishServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID must be greater than zero..
        /// </summary>
        internal static string ProductIdGreaterThanZero {
            get {
                return ResourceManager.GetString("ProductIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &apos;{0}&apos; is not active..
        /// </summary>
        internal static string ProductIsNotActive {
            get {
                return ResourceManager.GetString("ProductIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was not found in this session..
        /// </summary>
        internal static string ProductNotFoundInSession {
            get {
                return ResourceManager.GetString("ProductNotFoundInSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quantity can only be updated for active sessions..
        /// </summary>
        internal static string ProductQuantityCanOnlyBeUpdatedForActiveSession {
            get {
                return ResourceManager.GetString("ProductQuantityCanOnlyBeUpdatedForActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products can only be added to active sessions..
        /// </summary>
        internal static string ProductsCanOnlyBeAddedToActiveSession {
            get {
                return ResourceManager.GetString("ProductsCanOnlyBeAddedToActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Products can only be cleared from active sessions..
        /// </summary>
        internal static string ProductsCanOnlyBeClearedFromActiveSession {
            get {
                return ResourceManager.GetString("ProductsCanOnlyBeClearedFromActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products can only be removed from active sessions..
        /// </summary>
        internal static string ProductsCanOnlyBeRemovedFromActiveSession {
            get {
                return ResourceManager.GetString("ProductsCanOnlyBeRemovedFromActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be greater than zero..
        /// </summary>
        internal static string QuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is already added to this session..
        /// </summary>
        internal static string ServiceAlreadyAddedToSession {
            get {
                return ResourceManager.GetString("ServiceAlreadyAddedToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service can only be added to an active session..
        /// </summary>
        internal static string ServiceCanOnlyBeAddedToActiveSession {
            get {
                return ResourceManager.GetString("ServiceCanOnlyBeAddedToActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service created successfully..
        /// </summary>
        internal static string ServiceCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service deleted successfully..
        /// </summary>
        internal static string ServiceDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ID must be greater than zero..
        /// </summary>
        internal static string ServiceIdGreaterThanZero {
            get {
                return ResourceManager.GetString("ServiceIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not active..
        /// </summary>
        internal static string ServiceIsNotActive {
            get {
                return ResourceManager.GetString("ServiceIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found..
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service price must be greater than zero..
        /// </summary>
        internal static string ServicePriceGreaterThanZero {
            get {
                return ResourceManager.GetString("ServicePriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service restored successfully..
        /// </summary>
        internal static string ServiceRestoredSuccessfully {
            get {
                return ResourceManager.GetString("ServiceRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service retrieved successfully..
        /// </summary>
        internal static string ServiceRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services retrieved successfully..
        /// </summary>
        internal static string ServicesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("ServicesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service updated successfully..
        /// </summary>
        internal static string ServiceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ServiceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with the same name already exists..
        /// </summary>
        internal static string ServiceWithSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("ServiceWithSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID must be greater than zero..
        /// </summary>
        internal static string SessionIdGreaterThanZero {
            get {
                return ResourceManager.GetString("SessionIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found..
        /// </summary>
        internal static string SessionNotFound {
            get {
                return ResourceManager.GetString("SessionNotFound", resourceCulture);
            }
        }
    }
}
